### ISSUE TITLE
clear() does not seem to clear user defaults

### ISSUE THREAD

**Issue by maguro** [SwiftKitz/Storez#9]
The following code passes the first time.  When the test is run a second time it fails. 

    func testUserDefaultsBuggyClear() {

        var testStore = UserDefaultsStore(suite: "io.kitz.storez.test")
        let key = Key<GlobalNamespace, Int?>(id: "foo", defaultValue: nil)

        testStore.clear()

        XCTAssertNil(testStore.get(key))
        testStore.set(key, value: 666)
        XCTAssertEqual(testStore.get(key), 666)

        testStore.clear()
        XCTAssertNil(testStore.get(key))

        testStore = UserDefaultsStore(suite: "io.kitz.storez.test")

        XCTAssertNil(testStore.get(key))

        testStore.set(key, value: 666)
    }

Run the following code several times and it eventually will always pass:

    func testUserDefaultsClear() {

        var testStore = UserDefaultsStore(suite: "io.kitz.storez.test")
        let key = Key<GlobalNamespace, Int?>(id: "foo", defaultValue: nil)

        testStore.clear()

        XCTAssertNil(testStore.get(key))
        testStore.set(key, value: 666)
        XCTAssertEqual(testStore.get(key), 666)

        testStore.clear()
        XCTAssertNil(testStore.get(key))

        testStore = UserDefaultsStore(suite: "io.kitz.storez.test")

        XCTAssertNil(testStore.get(key))

        testStore.set(key, value: 666)

        testStore.clear()
    }

**Comment by Mazyod** [comment]
Thanks for sharing this issue. Storez **definitely** clears the user defaults properly in production on a real device, but unfortunately, due to some optimizations or whatnot on iOS simulator, when running tests specifically, things can go haywire. It's not the fault of the library. To easily prove that, simply run the tests against a MacOS target, and see it breeze through without issues.

I have made fixes to the unit tests, which haven't been released under a tag yet. You can see the change in the following comment:

https://github.com/SwiftKitz/Storez/commit/693b25c6ce32e3c7ed9f531facf308cc44db9d5c

**Comment by maguro** [comment]
Ahh, I was wondering why that bit of code was there.  Tks!
